version: "3"

volumes:
  geth: {}
  prometheus: {}
  grafana: {}

services:
  geth:
    image: "exodusmovement/geth:1.11.8-003"
    container_name: geth
    environment:
      - GETH_JSONRPC_INTERFACE=all
      - GETH_ARGUMENTS=--light
    volumes:
      - geth:/home/geth/.local/share/io.geth.ethereum/

  geth-exporter:
    build:
      context: ../
    container_name: geth-exporter
    environment:
      - GETH_EXPORTER_NODE=http://geth:8545/
    depends_on:
      - geth
    ports:
      - 8000:8000

  prometheus:
    image: prom/prometheus:v2.1.0
    container_name: prometheus
    depends_on:
      - geth-exporter
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus
    command:
      - "--config.file=/etc/prometheus/prometheus.yml"
      - "--storage.tsdb.path=/prometheus"
      - "--web.console.libraries=/usr/share/prometheus/console_libraries"
      - "--web.console.templates=/usr/share/prometheus/consoles"

  grafana:
    image: grafana/grafana:5.2.1
    container_name: grafana
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=foobar
      - GF_USERS_ALLOW_SIGN_UP=false
    depends_on:
      - prometheus
    volumes:
      - grafana:/var/lib/grafana
      - ./grafana/provisioning/:/etc/grafana/provisioning/
    ports:
      - 3000:3000
